---
targets:
  demo:
    services:
      - Service
    package: github.com/foomo/gotsrpc/demo
    out: /tmp/test.ts 
mappings:
  github.com/foomo/gotsrpc/demo:
    module: GoTSRPC.Demo
    out: /tmp/test-files.ts
