---
targets:
  demo:
    module: GoTSRPC.Demo
    services:
      /service/demo: Service
    package: github.com/foomo/gotsrpc/demo
    out: /tmp/test.ts
    rpc: true
mappings:
  github.com/foomo/gotsrpc/demo:
    module: GoTSRPC.Demo
    out: /tmp/test-files-demo.ts
  github.com/foomo/gotsrpc/demo/nested:
    module: GoTSRPC.Demo.Nested
    out: /tmp/test-files-demo-nested.ts
