---
targets:
  demo:
    module: GoTSRPC.Demo
    services:
      - Service
    package: github.com/foomo/gotsrpc/demo
    out: /tmp/test.ts 
mappings:
  github.com/foomo/gotsrpc/demo:
    module: GoTSRPC.Demo
    out: /tmp/test-files.ts
  github.com/foomo/gotsrpc/demo/nested:
    module: GoTSRPC.Demo.Nested
    out: /tmp/test-files.ts
